### ISSUE TITLE
Bug: second struct data when including a second page

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#101]
When including a page (without struct data) into a page with struct data, than the data is displayed twice: on top and on top of the included page/section. see foo:doku.php?id=projects:secondtest:start

**Comment by micgro42** [comment]
The referenced paged has currently a workaround in place. The problem can still be seen in the old version:
``foo:doku.php?id=projects:secondtest:start&rev=1465384666``

The problem seems to be that including another page means including another "first" headline after which the generation of another struct data display is triggered. The woprkaround is to make sure that the included headline is not the first on the included page.

**Comment by micgro42** [comment]
Has been fixed in #102
