### ISSUE TITLE
Empty field of page type with title enabled is not treated as empty

### ISSUE THREAD

**Issue by micgro42** [cosmocode/dokuwiki-plugin-struct#148]
This might be related to #114, but also affects the data shown on the page itself.

**Comment by splitbrain** [comment]
I'm not sure I understand what exactly the bug is here. Don't we store empty strings for all Types when a field is empty?

**Comment by micgro42** [comment]
No, we store `null` for all types. Except for the page type, apparently.

**Comment by micgro42** [comment]
Some screenshots that illustrate the problem:
![foopattern](https://cloud.githubusercontent.com/assets/7372507/17553612/08814024-5f07-11e6-8c39-b871d9dfe539.png)
![aggrbar](https://cloud.githubusercontent.com/assets/7372507/17553614/08a50a68-5f07-11e6-9d7c-77e0bf11d10e.png)
![rqpattern](https://cloud.githubusercontent.com/assets/7372507/17553613/08a1913a-5f07-11e6-93d0-9423f1dfdbad.png)
However the error only appears when the title-option is used. I'll adjust this issues title accordingly.

**Comment by splitbrain** [comment]
Problem was not that JSON was returned. The problem was that isEmptyRow did not check against the raw value.

**Comment by splitbrain** [comment]
Okay this a bit more complicated than I thought. I think we need to fix our rawValue concept which is currently all over the place. I'd like to make it like this:

* Change the ``Value`` class
  * [ ] to have a ``getRawValue`` method
  * [ ] to have a ``isEmpty`` method
* Change the ``DataSchema`` aka ``AccessTable`` class and
  *  [ ] remove the ``optionRawValue`` mechanism
  *  [ ] instead ``getData()`` returns ``Value[]``
  *  [ ] and ``getDataArray()`` always returns an array of raw values
* [ ] Change all code occurrences to make use of this new system

Because this affects the AccessTable class, I would like to either
  * make these changes in the lookup branch only
  * merge the lookup branch first
