### ISSUE TITLE
Activating 'struct' plugin leads to blank page

### ISSUE THREAD

**Issue by fdmgit** [cosmocode/dokuwiki-plugin-struct#313]
I've install vanilla DokuWiki (latest stable version). 
Logged in and installed 'sqlite' plugin. Then installed 'struct' plugin and boom I get a blank page. Both plugins downloaded and installed through DokuWiki extension manager.

Environment: 
Ubuntu 16.04
PHP7 with sqlite3 / pdo_sqlite modules enabled

Any hints ?

**Comment by mukrop** [comment]
Just ran into the same thing. Did you also install the sqlite extension for PHP? (see https://www.dokuwiki.org/plugin:sqlite)

On Ubuntu, I did `sudo apt install php7.0-sqlite3`

**Comment by fdmgit** [comment]
Yes, on Ubuntu the sqlite module for PHP is installed and enabled. I checked that before installing the sqlite plugin on DokuWiki.

**Comment by micgro42** [comment]
A blank page sounds like a fatal error. Can you have a look at what your error log says?

It's been some time since I used Ubuntu, but I think you can find it at `/var/log/apache2/error.log` or something similar.

**Comment by boqapt** [comment]
On Ubuntu I've just installed apache2, PHP 7.0.22-0ubuntu0.16.04.1, dokuwiki 2014-09-29d "Hrun" - everything from Ubuntu repo. In fresh dokuwiki installed sqlite and struct plugins from Admin panel. Having blank start page and error in log in that moment

> PHP Fatal error: 
 Uncaught Error: Class 'dokuwiki\\plugin\\struct\\meta\\Assignments' not found in /var/lib/dokuwiki/lib/plugins/struct/action/cache.php:46
Stack trace:
#0 /usr/share/dokuwiki/inc/events.php(204): action_plugin_struct_cache->handle_cache_schemachange(Object(Doku_Event), NULL)
#1 /usr/share/dokuwiki/inc/events.php(67): Doku_Event_Handler->process_event(Object(Doku_Event), 'BEFORE')
#2 /usr/share/dokuwiki/inc/events.php(103): Doku_Event->advise_before(true)
#3 /usr/share/dokuwiki/inc/events.php(231): Doku_Event->trigger(Array, true)
#4 /usr/share/dokuwiki/inc/cache.php(53): trigger_event('PARSER_CACHE_US...', Object(cache_renderer), Array)
#5 /usr/share/dokuwiki/inc/parserutils.php(109): cache->useCache()
#6 /usr/share/dokuwiki/inc/parserutils.php(76): p_cached_output('/var/lib/dokuwi...', 'xhtml', 'start')
#7 /usr/share/dokuwiki/inc/html.php(246): p_wiki_xhtml('start', 0, true, '')
#8 /usr/share/dokuwiki/inc/template.php(105): html_show()
#9 /usr/share/dokuwiki/inc/events.php(108): tpl_content_core('show')
#10 /usr/ in /var/lib/dokuwiki/lib/plugins/struct/action/cache.php on line 46, referer: http://localhost/dokuwiki/doku.php?id=wiki:syntax

I've looked into code. It seems that file /var/lib/dokuwiki/lib/plugins/struct/meta/Assignments.php for some reason is not included. May be the reason is I've made some errors when setting up the server?

**Comment by micgro42** [comment]
Hrun is 3 major versions of DokuWiki behind and the struct plugin is not compatible with it. Please have a look at the "Compatible with DokuWiki" widget on https://www.dokuwiki.org/plugin:struct.

**Please contact the maintainer of the Ubuntu repo and let them know, that they should update DokuWiki to the current version.**

**Comment by graceful-phoenix** [comment]
The same thing happened to me now.
A month ago I was trying openSUSE Linux, I had DokuWiki installed there from a tarball, and it worked smoothly with sqlite and struct plugins installed.
Now I returned to Ubuntu Linux (18.10), and installed DokuWiki from the very same tarball (it was backed up), had it set up with Nginx (1.15.5) and php7.2-fpm (from packages). It worked until I installed struct and sqlite plugins through the Extension Manager. Blank page immediately, I did not even had a chance to use the plugin in any way. I see this error in /var/log/nginx/error.log:

2019/02/25 15:59:53 [error] 29751#29751: *12 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in /var/www/html/dokuwiki/lib/plugins/struct/helper/db.php:38
Stack trace:
#0 /var/www/html/dokuwiki/lib/plugins/struct/helper/db.php(22): helper_plugin_struct_db->init()
#1 /var/www/html/dokuwiki/inc/plugincontroller.class.php(109): helper_plugin_struct_db->__construct()
#2 /var/www/html/dokuwiki/inc/pluginutils.php(45): Doku_Plugin_Controller->load('helper', 'struct_db', false, false)
#3 /var/www/html/dokuwiki/lib/plugins/struct/meta/PageMeta.php(20): plugin_load('helper', 'struct_db')
#4 /var/www/html/dokuwiki/lib/plugins/struct/action/title.php(42): dokuwiki\plugin\struct\meta\PageMeta->__construct('start')  
#5 /var/www/html/dokuwiki/inc/events.php(229): action_plugin_struct_title->handle_meta(Object(Doku_Event), NULL)
#6 /var/www/html/dokuwiki/inc/events.php(79): Doku_Event_Handler->process_event(Object(Doku_Event), 'AFTER')
#7 /var/www/html/dokuwiki/inc/parserutils.php(502): Doku_Event->advise_after()
#8 /var/w" while reading response header from upstream, client: 127.0.0.1, server: dokuwiki.localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php7.2-fpm.sock:", host: "localhost"

Restarting the nginx and php7.2-fpm services doesn't help.
I manually removed the struct plugin, and DokuWiki local site is available again.
Installation from a tarball from the official site means that _I have relatively new (stable) version._

**Comment by graceful-phoenix** [comment]
I forgot to add: I have 2018-04-22 "Greebo" version of DokuWiki installed. It is compatible with the plugin.

**Comment by micgro42** [comment]
@graceful-phoenix It seems like you are missing the pdosqlite extension on your server. That extension is a prerequisite for the sqlite plugin, which in turn is a prerequisite for the struct plugin. If you install pdo-sqlite, all should work as expected.

Nonetheless, there should be no fatal error in this case. Thus, I opened #440 to track that issue.
