### ISSUE TITLE
Page and lookup schemas: Access permission policy not consistent. Suggestion to make it configurable 

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#321]
It seems, that (read) access to data stored in page schemas is only allowed, if the user has also at least read permission to the associated wiki page itself.  This seems not consistent with how access to lookup schemas is handled: Data stored in lookup schemas are also readable by users w/o read permission on the page, where the lookup is defined.  Please correct me if I am wrong.

A typical application of page schemas for us is to keep "public" information on otherwise private pages.  The public information - in the page schema - should be readable/accessible by anyone, while the page content itself is kept hidden.

I suggest to make this configurable either per schema or per field and to default the permission to "read for everyone" for both, lookup and page schemas

**Comment by micgro42** [comment]
Thank you for your input. 🙂

You describe the way the plugin is intended and designed to work. The struct data in page-schemas is metadata associated with the specific page and hence shares the page's access rules. It can be better aggregated and entered, but it is not intended to split content in order to circumvent ACL.

Data in lookup-schemas is not associated with any page, you just happen to need a page where you create the form to enter data into the schema. The data in lookup-schemas is basically always public. You can restrict who can edit data in lookup-schemas in the schema editor.

**Comment by fthommen** [comment]
Then could this please be made clear(er) in the documentation?

**Comment by splitbrain** [comment]
It's a wiki,  please feel free to add to the documentation where it falls short.
