### ISSUE TITLE
Previewing a page adds empty lines to "Wiki" type fields

### ISSUE THREAD

**Issue by fthommen** [cosmocode/dokuwiki-plugin-struct#324]
On each klick on the "Preview" button after each line in "Wiki" type field an additional linebreak is added.  see the two images:

a) before previewing the page:
![pageschema_wikifield_1](https://user-images.githubusercontent.com/279232/28476941-454edaa6-6e52-11e7-8b72-04d6d462ac09.png)

b) after previewing the page:
![pageschema_wikifield_2](https://user-images.githubusercontent.com/279232/28476947-48117afa-6e52-11e7-91e9-e61adbfc0c40.png)

- DokuWiki version: Release 2017-02-19b "Frusterick Manners"
- Plugin version: 2017-07-11
- Schema type: Page schema

f.

**Comment by fthommen** [comment]
Can nobody confirm this bug?  We already had the situation, that after a long editing session with lots of previews, these fields got so long that could not be handled by the struct plugin any more (page stuck)

**Comment by rottaran** [comment]
I can confirm this bug. First, it was not visible because I used the fastwiki plugin, which loads just the preview via AJAX. Without fastwiki, preview loads the whole page and, then, an empty line was added after each original line. Really annoying.

The data is correctly sent as HTTP Post variable to the server. Then, it is read as input data in createForm() in action/edit.php and arrives at setValue() in meta/Value.php. On this way it is touched by rawValue() from AbstractBaseType but this does nothing. Finally, the new form's HTML output is created in valueEditor() of types/Wiki.php. There, formText() from Dokuwiki's inc/common.php is used. This transforms \n to \r\n and does html escaping. However, the inverse cleanText() is never called on the input, except in Wiki::validate(), which is called only when actually saving the page.
