### ISSUE TITLE
Feature Request: Pre-defined struct schema

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#340]
I think it could be useful to have some pre-defined "special" struct schema. In my usecase I want to have events and contacts as stuct data. It would be nice to have the possibility to export single events or contacts to ical or vcard. So maybe a pre-defind but extendible struct schema could be a first step?

**Comment by splitbrain** [comment]
Schemas can already be exported as JSON files. It might make sense to share such predefined schemas for common use ceases in the wiki. Feel free to start doing that.

However for implementing additional features likes importing/exporting data as iCal, vCard, vcf or similar you would need a new plugin (like the structstatus or structgannt plugin) to add this additional features.

Since the latter is out of scope of this plugin, I'm closing this ticket. Might be worth to ask for such a plugin in the plugins wishlist forum.
