### ISSUE TITLE
Export to CSV in table view should include wiki fields

### ISSUE THREAD

**Issue by juliusverrel** [cosmocode/dokuwiki-plugin-struct#341]
Currently, CSV Export in the table view (e.g., struct lookup) seems to replace struct fields of type "wiki" by empty strings (""). CSV export of wiki fields is still possible through the schema editor, but this doesn't allow filtering and column selection. Is there an easy fix for this?

**Comment by rottaran** [comment]
There is a difference between both CSV exports. The schema editor exports the raw data whereas the CSV export on the user pages exports what is visible to the visitors, e.g. with date formatting, prefix and postfix strings. Now, what should the wiki field export: The raw, not-rendered string like the Text type does? Or rendered to HTML and escaped as CSV table cell? Or some kind of text-alike rendering? Does it depend on the use case?

**Comment by juliusverrel** [comment]
Thanks for the replies and sorry for my delay. Either would work for my use case (I'm just using the wiki fields as long text fields, no markup); maybe others have a preference?

**Comment by fthommen** [comment]
In our current setup, we use it mostly for - sometimes quite long - unordered lists.  However generally thinking I'd say, that either raw Wikitext or text-alike rendering makes sense, rendered HTML doesn't.  Especially not, because a) - I guess - the rendered HTML code depends on the currently configured Wiki template, b) the user is normally interested in the information, not the HTML code.

To keep it simple (no additional rendering has to be implemented) I vote for raw Wiki text

**Comment by juliusverrel** [comment]
I agree to raw wiki text, thanks!
