### ISSUE TITLE
Lookup schemas return garbage data via XML-RPC after Hogfather upgrade

### ISSUE THREAD

**Issue by psy-q** [cosmocode/dokuwiki-plugin-struct#519]
When using the following data in a lookup schema called "personen":

```
Hillary
Bill
```

And assigning Bill as "besitzer" on a certain page, the `plugin.struct.getData` XML-RPC call returns garbage data:

```xml
<member>
  <name>besitzer</name>
  <value>
    <string>[&quot;&quot;,2]</string>
  </value>
</member>
```

We expect this instead:

```xml
<member>
  <name>besitzer</name>
  <value>
    <string>2</string>
  </value>
</member>
```

Using struct plugin 2020-07-29.

**Comment by annda** [comment]
By `we expect` do you mean the code that processes the API response? If so, the API consumer may have to be updated, because the simple integer IDs no longer exist in struct. They were removed together with schema types (see https://www.dokuwiki.org/plugin:struct:schemaedit) Since schema unification the IDs are what you see: a JSON-encoded composite ID consisting of page id and row id (in your case the page id is an empty string).

**Comment by psy-q** [comment]
OK, and will the response stay a HTML URL-encoded string, so we have to de-urlencode in the client?

**Comment by splitbrain** [comment]
That's XML encoded, because this is the XML-RPC API ;-). Your XML-RPC Client should decode that for you before passing it on to your code.

**Comment by psy-q** [comment]
I see! Sorry, I'm not the one implementing the client side here so I don't know exactly what which abstraction takes care of, I just wanted to be sure I know what's going on in the data :)
