### ISSUE TITLE
Allow setting access rules for Struct Data?

### ISSUE THREAD

**Issue by splitbrain** [cosmocode/dokuwiki-plugin-struct#53]
Inspired by http://stackoverflow.com/questions/35826232/dokuwiki-block-certain-sections-from-editing

We could make it possible to set who is allowed to edit structured data on a per schema basis. Would that be a good idea?

**Comment by micgro42** [comment]
This would mean a configuration field in which allowed Users/Groups can be entered and that defaults to @ALL otherwise?

Could be useful. However we would have to decide if this should also affect who is allowed to see the data from those schemas or aggregate it.

The struct plugin's entry form is so obvious, that we don't need to limit it to prevent accidental entries. I could see use for limiting edition the aggregation syntax. But the functionality mentioned in the link could be better provided by another plugin or maybe by integrating it into a template.

**Comment by splitbrain** [comment]
yeah limiting syntax is nearly impossible. using the include plugin is the best way to go.

Limiting the entry form on the other hand would be relatively simple. That's why I suggested it. I could imagine it being useful but it's open for discussion.

**Comment by splitbrain** [comment]
I just thought of another use case. Since our structured data is now completely independent from the page it self, it could theoretically be changed through other means than editing a page.

For example we could create a remote component to allow editing structured data via API. Or for example the plugin metadata on dokuwiki.org could be autosynced with github. It might be useful to make the structured data completely non-editable through the form by only allowing editing to a special "remote" or "api" group.

**Comment by stvoigt** [comment]
I think there are maybe use cases where you do not want some users to edit the struct data. But I do not see it in our use case so far. This would be a nice2have-feature IMHO.
The last mentioned point from @splitbrain would be really nice! Any form of batch editing without going to several pages, edit the pages (but only want to edit the data), change the data and save the page switch back to the overview/aggregation and repeat that cycle is very welcomed :)

**Comment by iainhallam** [comment]
At the moment, it seems like the direction of the struct plugin is following a lot of other CMSs that only try to do the easy thing of mapping URLs to types of object, so your namespaces would be your schema types. Getting away from this was exactly the reason I adopted DokuWiki; what if I want my namespaces to be departments, or systems, and then have different structured data spread all over the site?

For example, it would be fairly easy to build a database of products using structured data, but instead of treating all products as being in a separate are of the site, my departments manage their own product databases, sometimes several. With the current documentation, it looks like I'd have to add each set of products as a separate mapping, and couldn't then have other pages like README pages interspersed.

Why not let each page specify what schemas it is using and how many? Then this issue would truly be shallow; just look at the page ACL to determine who should be able to edit the data. Similarly for pages that aggregate data and present tables, etc. - use the existing ACL for that page. You could have a configuration option for the whole site that even behaves like the site index does. and checks whether structs are visible to the calling user before including them in aggregate data tables, etc.

It's a powerful security mechanism that adopts DokuWiki's flexibility, rather than becoming the custom data types of WordPress, which have very little place in an enterprise setting unless you program loads of custom security.

**Comment by splitbrain** [comment]
There is one field that needs to be added to the schema table (``editableby`` or something). It would hold a string that can be evaluated by our ``auth_memberof()`` function. When the field is empty, everyone may edit data in the schema. When the field is filled, only users matching the given users/groups may edit data in that schema.

Schemas not editable by the current user should not display in the page editor. The lookup editor should not accept edits by the user then (in fact the whole lookup JS initialization should fail early, too). The inline editor needs to check the permissions as well.

To configure the contents of the new field I would maybe add another tab in the schema editor (we may need to consolidate the various tabs a little more later).

**Comment by splitbrain** [comment]
this is implemented now. https://www.dokuwiki.org/plugin:struct:permissions
