### ISSUE TITLE
"Struct serial" input mask should not edit last entry but write a new one while being in wiki page edit mode

### ISSUE THREAD

**Issue by pippcat** [cosmocode/dokuwiki-plugin-struct#535]
This is a follow up of #526 and you may read there to learn about the setup and find some example data. After the fix there I'm facing another issue:

Everything works as expected if dokuwiki is in view mode and I use the struct serial form to enter new data.

If dokuwiki is in editor mode the struct serial form has the last entered data in it. Is that expected behaviour and if so is there still a way to change it? People here want to enter new data while being in the editor and then alter the struct data instead of making new entries without noticing. :cry:

**Comment by pippcat** [comment]
Just bumping this up because it's quite annoying and confuses users a lot: it's only possible to add data to the serial form while being in view mode. If edit mode is active, the form will show the data of the first entry of the page and if this data is altered, new data will not be displayed later. I'll attach a screencast and a screenshot to make things more clear..

![Peek 2021-01-24 22-14](https://user-images.githubusercontent.com/19587872/105643794-402f2600-5e92-11eb-8fac-58f7fdfe65c4.gif)

![Bildschirmfoto vom 2021-01-24 22-17-52](https://user-images.githubusercontent.com/19587872/105643786-386f8180-5e92-11eb-84e6-f1359c0499ef.png)

**Comment by annda** [comment]
Thanks for the screencast. It shows the buggy behavior that the **serial data** (`first entry`) shows up in your **page data** editor. The  fields should be empty at this point. The rest looks correct to me.

In other words, **serial data** (the table in view mode) and **page data** (edit mode) are supposed to be completely independent of each other. The bug is that in one special case they are not.

What you enter in edit mode is meant to update the previous struct data for that page. If you want to add data to a series, you have to use the **serial editor** in view mode.

I have pinpointed the source of the error thanks to your report but I need to make sure not to introduce any side effects when fixing it.
