### ISSUE TITLE
How to remove old schema assignments with serial data without breaking the aggregationeditor?

### ISSUE THREAD

**Issue by Chris75forumname** [cosmocode/dokuwiki-plugin-struct#666]
In the documentation I read here: https://www.dokuwiki.org/plugin:struct:schemaedit#schema_usage_for_data_mangement:
"Serial data can be also be bound to Wiki pages via the assignments manager."

Is that true? Is that even necessary, if serial data is automatically assigned to the page it was entered from? What is the point anyway to assign a schema to a page other than for page data? 
As I understand, each serial data can only be assigned to one page at a time and that is done by the serial editor, not the assignment manager.

I suggest to remove this sentence from the documentation, since I think it is misleading in the process of understanding, what serial data actually is.

Also on the documentation about the assignment manager, https://www.dokuwiki.org/plugin:struct:assignments, it should be stated explicitely, that the assignment manager is only needed and used for assignining page data to pages, and has no effect on serial and global data, whatsoever.

Can anyone please confirm or correct my thoughts! (I don't want to spread even more confusion by editing the documentation in the wrong direction!) 😃

**Comment by Chris75forumname** [comment]
I found confirmation of my thoughts in old revisions of the same pages. I changed those documentations as above proposed. I find it much less confusing now!

**Comment by Chris75forumname** [comment]
I am confused again. 

In my test wiki I have `serial aggregationeditors showing data that was input solely through this page` without any schema assignment whatsoever. Now, in my production wiki I have the same situation, a page with a  `serial aggregationeditor showing data that was input solely through this page`, however, when I first started to incorporate struct, I was confused and thinking, I had to assign the schema to the page beforehand, even with serial data. So I did that. Now, I was thinking, these old assignments weren't necessary in the first place, so I deleted them. 

To my suprise, the serial aggregationeditor on this page was now empty. 

So, what is going on here?? Has the necessety, to assign pages for serial data, changed at some point in the past?? Or has it something to do, with the later removal of the assignment?? I don't get it!

**Comment by annda** [comment]
Thanks for updating the docs. It is still true that the same schema **can be** used for pages and serial data stored on the same pages. But this is a rather exotic use case.

Your empty serial aggregation is indeed caused by removing the assignment to the page. The actual data is still in the database, but cannot be accessed.

We have to change the base SQL queries so that they properly differentiate between page data and serial data.

Until we have a solution, you can only restore access to your data directly in the database. In the table `schema_assignments` find the old assignment, where the field `assigned` is set to 0 and remove the row completely.
