### ISSUE TITLE
Bug: Delete struct elements

### ISSUE THREAD

**Issue by stvoigt** [cosmocode/dokuwiki-plugin-struct#69]
Right now we are unable to delete struct elements, see: Wizmo-Wiki struct projekt
(But I am not sure if this feature was already implemented?)

**Comment by splitbrain** [comment]
Please clarify: what exactly do you want to delete?

**Comment by stvoigt** [comment]
When defining a struct and you want to remove an element from that definition, that does not work. At least Julia had that problem @Wizmo, maybe she can show you directly...

**Comment by splitbrain** [comment]
There is no delete for schema fields, but you can disable them. This is a requirement to be able to access historic data.

**Comment by GJRobert** [comment]
Problematic scenario: wanted to a new field but later decided to abandon so leaving all the fields empty, but such obsolete fields (never been used) remain permanently, even with the possibility to be duplicated once and again by the editor when saving, because of "Label already exists in schema, second occurance was renamed to xx".

How should we avoid this?

**Comment by GJRobert** [comment]
**Problematic scenario**: wanted to a new field but later decided to abandon so leaving all the fields empty, but such obsolete fields (never been used) remain permanently, even with the possibility to be duplicated once and again by the editor when saving, because of "Label already exists in schema, second occurance was renamed to xx".

How should we avoid this?
