### ISSUE TITLE
Support other aggregation types

### ISSUE THREAD

**Issue by iainhallam** [cosmocode/dokuwiki-plugin-struct#90]
In the original data plugin, as well as a table, you can pull out a list or cloud; are these likely to be supported in struct?

**Comment by splitbrain** [comment]
Yes, implementing other aggregation types was planned. However since those other types are rarely used in the data plugin they had very low priority for the struct plugin and weren't implemented in the first development cycle.

PRs welcome

**Comment by regul8or** [comment]
I second this feature. Just when I started to use dokuwiki as a replacement for delicious and evernote, I found table aggregation too restrictive for this purpose.

More info for the use case here: https://forum.dokuwiki.org/post/53314

**Comment by eivdas** [comment]
I held off the move to struct because I need datalist, as well as datacloud...

**Comment by Laynee** [comment]
I've built a music database for all my favourite albums. It's awesome with de data plugin because you can generate a tag cloud for all the genres in your collection (Art Rock, Jazz, Memphis Blues...). You instantly see witch genres are the most popular, and it's beautiful ! So I stay with the data plugin for now. 

A tag cloud works really well for all "collections" databases : movies, music, video games, links... There are so much use cases !

**Comment by splitbrain** [comment]
list and cloud have been implemented
